# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: Kubernetes.Krew
PackageVersion: 0.4.4
InstallerType: portable
ReleaseDate: 2023-07-13
Commands:
- kubectl-krew
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew.exe
  InstallerSha256: dcbc1acd1009dba2b5d900043c6b8b571bbe418a4556eec070e7d4efcbddc766
ManifestType: installer
ManifestVersion: 1.5.0
